/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/prisons/{prisonCode}/staff/{staffId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve staff details for a specific staff member.
     * @description Get details and stats for the specified member of prison staff along with their policy staff role and status.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['getStaffDetails']
    /**
     * Update staff details for a specific staff member.
     * @description Update staff details for a specific staff member.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    put: operations['modifyStaffDetails']
    post?: never
    /**
     * Delete staff details for a specific staff member.
     * @description Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    delete: operations['removeStaffRole']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonCode}/prisoners/allocations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Update allocations for a given prison.
     * @description Update allocations for a given prison.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    put: operations['manageAllocations']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonCode}/policies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve policies for a specific prison.
     * @description Retrieve policies for a specific prison.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['getPrisonPolicies']
    /**
     * Update policies for a specific prison.
     * @description Update policies for a specific prison.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    put: operations['setPrisonPolicies']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonCode}/configurations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve prison configuration for the supplied policy.
     * @description Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['getPrisonConfiguration']
    /**
     * Update prison configuration for the supplied policy.
     * @description Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    put: operations['setPrisonConfiguration']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/staff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retrieve staff details from within a given prison.
     * @description Retrieve details for all staff members from within a given prison that match a query.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    post: operations['searchStaff']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/staff/{staffId}/recorded-events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retrieve a list of recorded events for a staff member.
     * @description Retrieve a list of recorded events for a staff member.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    post: operations['searchStaffRecordedEvents']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/staff-allocations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Search staff details from within a given prison.
     * @description Search prison staff including filtering those that have and do not have the policy staff role.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    post: operations['searchAllocatableStaff']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/prisoners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retrieve a list of people for a prison.
     * @description Retrieve a list of people for a prison that match a query.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    post: operations['searchPeople']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/subject-access-request': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Provides content for a prisoner to satisfy the needs of a subject access request on their behalf
     * @description Requires role SAR_DATA_ACCESS or additional role as specified by hmpps.sar.additionalAccessRole configuration.
     *
     *     Requires one of the following roles:
     *     * SAR_DATA_ACCESS
     *     * SAR_DATA_ACCESS
     */
    get: operations['getSarContentByReference']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reference-data/{domain}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve reference data for a specific domain.
     * @description Get ordered available options for the supplied reference data domain
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['findReferenceDataForDomain']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonCode}/statistics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve prison statistics for the supplied policy.
     * @description Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['getPrisonStatistics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisons/{prisonCode}/prisoners/allocation-recommendations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieves a list of recommended allocations for a given prison.
     * @description Retrieves a list of recommended allocations for a given prison.
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['getAllocationRecommendations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisoners/{prisonNumber}/allocations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieves current allocations for a given prisoner
     * @description Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS_UI
     */
    get: operations['getAllocations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/prisoners/{personIdentifier}/allocations/current': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieves current allocations for a given prisoner
     * @description Retrieves current allocations for a given prisoner
     *
     *     Requires one of the following roles:
     *     * ROLE_ALLOCATIONS__ALLOCATIONS__RO
     */
    get: operations['getCurrentAllocation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Request to patch the configuration for a staff. */
    StaffDetailsRequest: {
      status: string
      capacity: number
      /** @example 1980-01-01 */
      reactivateOn?: string
      staffRole: components['schemas']['StaffRoleRequest']
      deactivateActiveAllocations: boolean
    }
    StaffRoleRequest: {
      position: string
      scheduleType: string
      hoursPerWeek: number
      /** @example 1980-01-01 */
      fromDate: string
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      errorCode?: string
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    PersonStaffAllocation: {
      personIdentifier: string
      /** Format: int64 */
      staffId: number
      allocationReason: string
    }
    PersonStaffAllocations: {
      allocations: components['schemas']['PersonStaffAllocation'][]
      deallocations: components['schemas']['PersonStaffDeallocation'][]
    }
    PersonStaffDeallocation: {
      personIdentifier: string
      /** Format: int64 */
      staffId: number
      deallocationReason: string
    }
    PolicyEnabled: {
      /** @enum {string} */
      policy: 'KEY_WORKER' | 'PERSONAL_OFFICER'
      enabled: boolean
    }
    PrisonPolicies: {
      policies: components['schemas']['PolicyEnabled'][]
    }
    /** @description Request body for updating a prison's key worker configuration. */
    PrisonConfigRequest: {
      /** @description Indicates whether the key worker feature is enabled. */
      isEnabled: boolean
      /** @description Indicates whether the auto allocation of key workers is enabled. */
      allowAutoAllocation: boolean
      /**
       * Format: int32
       * @description The maximum number of prisoners that can be allocated to a key worker.
       */
      capacity: number
      /**
       * Format: int32
       * @description The frequency in weeks that key workers should have a session with their allocated prisoners.
       */
      frequencyInWeeks: number
      /** @description Indicates whether the prison has any prisoners with high complexity needs. */
      hasPrisonersWithHighComplexityNeeds?: boolean
      /**
       * @description The sort order used for displaying key workers when assigning to prisoners.
       * @enum {string}
       */
      allocationOrder: 'BY_ALLOCATIONS' | 'BY_NAME'
    }
    PrisonConfigResponse: {
      /** @description Indicates whether the key worker feature is enabled. */
      isEnabled: boolean
      /** @description Indicates whether the prison has any prisoners with high complexity needs. */
      hasPrisonersWithHighComplexityNeeds: boolean
      /** @description Indicates whether the auto allocation of key workers is enabled. */
      allowAutoAllocation: boolean
      /**
       * Format: int32
       * @description The maximum number of prisoners that can be allocated to a key worker.
       */
      capacity: number
      /**
       * Format: int32
       * @description The frequency in weeks that key workers should have a session with their allocated prisoners.
       */
      frequencyInWeeks: number
      /**
       * @description The sort order used for displaying key workers when assigning to prisoners.
       * @enum {string}
       */
      allocationOrder: 'BY_ALLOCATIONS' | 'BY_NAME'
    }
    StaffSearchRequest: {
      query?: string
      /** @enum {string} */
      status:
        | 'ALL'
        | 'ACTIVE'
        | 'UNAVAILABLE_ANNUAL_LEAVE'
        | 'UNAVAILABLE_LONG_TERM_ABSENCE'
        | 'UNAVAILABLE_NO_PRISONER_CONTACT'
        | 'INACTIVE'
      hasPolicyStaffRole?: boolean
    }
    CodedDescription: {
      code: string
      description: string
    }
    StaffRoleInfo: {
      position: components['schemas']['CodedDescription']
      scheduleType: components['schemas']['CodedDescription']
      hoursPerWeek: number
      /** Format: date */
      fromDate: string
      /** Format: date */
      toDate?: string
    }
    StaffSearchResponse: {
      content: components['schemas']['StaffSearchResult'][]
    }
    StaffSearchResult: {
      /** Format: int64 */
      staffId: number
      firstName: string
      lastName: string
      status: components['schemas']['CodedDescription']
      /** Format: int32 */
      capacity: number
      /** Format: int32 */
      allocated: number
      /** Format: int32 */
      numberOfSessions: number
      /** Format: int32 */
      numberOfEntries: number
      staffRole?: components['schemas']['StaffRoleInfo']
      username: string
      email?: string
    }
    RecordedEventRequest: {
      types: ('SESSION' | 'ENTRY')[]
      /** Format: date */
      from?: string
      /** Format: date */
      to?: string
    }
    RecordedEventAmendment: {
      /** Format: date-time */
      createdAt: string
      authorDisplayName: string
      text: string
    }
    RecordedEventPrisoner: {
      prisonerNumber: string
      firstName: string
      lastName: string
    }
    RecordedEventResponse: {
      recordedEvents: components['schemas']['StaffRecordedEvent'][]
    }
    StaffRecordedEvent: {
      prisoner: components['schemas']['RecordedEventPrisoner']
      type: components['schemas']['CodedDescription']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      occurredAt: string
      text: string
      amendments: components['schemas']['RecordedEventAmendment'][]
    }
    /** @description Search for allocatable staff */
    AllocatableSearchRequest: {
      /** @description Query string to search for. */
      query?: string
      /**
       * @description The filter to apply to the results.
       * @default ALL
       * @enum {string}
       */
      status: 'ACTIVE' | 'INACTIVE' | 'ALL'
    }
    /** @description A list of allocatable staff members. */
    AllocatableSearchResponse: {
      content: components['schemas']['AllocatableSummary'][]
    }
    /** @description Staff member summary information. */
    AllocatableSummary: {
      /**
       * Format: int64
       * @description The staff member's identifier.
       */
      staffId: number
      /** @description The staff member's first name. */
      firstName: string
      /** @description The staff member's last name. */
      lastName: string
      /** @description The staff member's current status. */
      status: components['schemas']['CodedDescription']
      /**
       * Format: int32
       * @description The staff member's capacity.
       */
      capacity: number
      /**
       * Format: int32
       * @description The number of prisoners currently allocated to this staff member.
       */
      allocated: number
      /** @description The details of the staff member's role. */
      staffRole: components['schemas']['StaffRoleInfo']
      /** @description The statistics for this staff member. */
      stats?: components['schemas']['StaffCountStats']
    }
    RecordedEventCount: {
      /** @enum {string} */
      type: 'SESSION' | 'ENTRY'
      /** Format: int32 */
      count: number
    }
    StaffCountStats: {
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      /** Format: int32 */
      projectedComplianceEvents: number
      /** Format: int32 */
      recordedComplianceEvents: number
      recordedEvents: components['schemas']['RecordedEventCount'][]
      /** Format: double */
      complianceRate: number
    }
    PersonSearchRequest: {
      query?: string
      cellLocationPrefix?: string
      excludeActiveAllocations: boolean
    }
    PersonSearchResponse: {
      content: components['schemas']['PrisonerSummary'][]
    }
    PrisonerSummary: {
      personIdentifier: string
      firstName: string
      lastName: string
      location?: string
      hasHighComplexityOfNeeds: boolean
      hasAllocationHistory: boolean
      staffMember?: components['schemas']['StaffAllocationCount']
      relevantAlertCodes: string[]
      /** Format: int32 */
      remainingAlertCount: number
    }
    StaffAllocationCount: {
      /** Format: int64 */
      staffId: number
      firstName: string
      lastName: string
      /** Format: int32 */
      allocationCount: number
    }
    Attachment: {
      /**
       * Format: int32
       * @description The number of the attachment which will match any corresponding reference in the content section
       */
      attachmentNumber: number
      /** @description The name or description of the attachment which will be included in the report */
      name: string
      /** @description The content type of the attachment */
      contentType: string
      /** @description The url to be used to download the attachment file */
      url: string
      /**
       * Format: int32
       * @description The size of the attachment file in bytes
       */
      filesize: number
      /** @description The filename of attachment file */
      filename: string
    }
    HmppsSubjectAccessRequestContent: {
      /** @description The content of the subject access request response */
      content: unknown
      /** @description The details of any attachments for the subject access request response */
      attachments?: components['schemas']['Attachment'][]
    }
    PrisonStatSummary: {
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      /** Format: int32 */
      totalPrisoners?: number
      /** Format: int32 */
      highComplexityOfNeedPrisoners?: number
      /** Format: int32 */
      eligiblePrisoners?: number
      /** Format: int32 */
      prisonersAssigned?: number
      /** Format: int32 */
      eligibleStaff?: number
      recordedEvents: components['schemas']['RecordedEventCount'][]
      /** Format: int32 */
      avgReceptionToAllocationDays?: number
      /** Format: int32 */
      avgReceptionToRecordedEventDays?: number
      /** Format: int32 */
      projectedRecordedEvents?: number
      /** Format: double */
      percentageAssigned?: number
      /** Format: double */
      recordedEventComplianceRate?: number
    }
    PrisonStats: {
      prisonCode: string
      current: components['schemas']['PrisonStatSummary']
      previous: components['schemas']['PrisonStatSummary']
      hasPrisonersWithHighComplexityOfNeed: boolean
    }
    Allocation: {
      prisoner: components['schemas']['Prisoner']
      stats: components['schemas']['StaffCountStats']
      latestSession?: components['schemas']['LatestSession']
    }
    LatestSession: {
      /** Format: date */
      occurredAt: string
    }
    Prisoner: {
      prisonNumber: string
      firstName: string
      lastName: string
      csra?: string
      cellLocation?: string
      /** Format: date */
      releaseDate?: string
      relevantAlertCodes: string[]
      /** Format: int32 */
      remainingAlertCount: number
    }
    StaffDetails: {
      /** Format: int64 */
      staffId: number
      firstName: string
      lastName: string
      status: components['schemas']['CodedDescription']
      prison: components['schemas']['CodedDescription']
      /** Format: int32 */
      capacity: number
      /** Format: int32 */
      allocated: number
      allocations: components['schemas']['Allocation'][]
      stats?: components['schemas']['StaffStats']
      /** Format: date */
      reactivateOn?: string
      staffRole?: components['schemas']['StaffRoleInfo']
    }
    StaffStats: {
      current: components['schemas']['StaffCountStats']
      previous: components['schemas']['StaffCountStats']
    }
    /** @description Details of a staff member available for allocation. */
    AllocationStaff: {
      /**
       * Format: int64
       * @description The staff member's unique identifier.
       */
      staffId: number
      /** @description The staff member's first name. */
      firstName: string
      /** @description The staff member's last name. */
      lastName: string
      /** @description The staff member's current status. */
      status: components['schemas']['CodedDescription']
      /**
       * Format: int32
       * @description The staff member's capacity.
       */
      capacity: number
      /**
       * Format: int32
       * @description The number of prisoners currently allocated to this staff member.
       */
      allocated: number
    }
    /** @description The recommended allocation for a prisoner. */
    RecommendedAllocation: {
      /** @description The prisoner's identifier. */
      personIdentifier: string
      /** @description The staff member recommended to be allocated to this prisoner. */
      staff: components['schemas']['AllocationStaff']
    }
    /** @description Allocation Recommendation */
    RecommendedAllocations: {
      /** @description The list of recommended allocations. */
      allocations: components['schemas']['RecommendedAllocation'][]
      /** @description The list of prisoners that do not have an active key worker. */
      noAvailableStaffFor: string[]
      /** @description The list of staff members available for allocation. */
      staff: components['schemas']['AllocationStaff'][]
    }
    /** @description Details relating to when an action was performed. */
    Actioned: {
      /**
       * Format: date-time
       * @description The date and time when the action was performed.
       */
      at: string
      /** @description The name of the user who performed the action. */
      by: string
      /** @description The reason for the action. */
      reason: components['schemas']['CodedDescription']
    }
    /** @description Staff allocation details. */
    StaffAllocation: {
      /** @description Indicates if the staff member is currently assigned to this prisoner. */
      active: boolean
      /** @description The details of the staff member. */
      staffMember: components['schemas']['StaffSummary']
      /** @description The prison where the staff member is assigned to this prisoner. */
      prison: components['schemas']['CodedDescription']
      /** @description The details regarding when the staff member was allocated to this prisoner. */
      allocated: components['schemas']['Actioned']
      /** @description The details regarding when the staff member was de-allocated from this prisoner. */
      deallocated?: components['schemas']['Actioned']
    }
    /** @description Prisoner allocation history details. */
    StaffAllocationHistory: {
      /**
       * @description The identifier for the prisoner.
       * @example A12345
       */
      prisonNumber: string
      /** @description The list of allocations for this prisoner. */
      allocations: components['schemas']['StaffAllocation'][]
    }
    StaffSummary: {
      /** Format: int64 */
      staffId: number
      firstName: string
      lastName: string
    }
    /** @description Details of the user who recorded the event. */
    Author: {
      /**
       * Format: int64
       * @description The unique identifier for the user.
       */
      staffId: number
      /** @description The first name of the user. */
      firstName: string
      /** @description The last name of the user. */
      lastName: string
      /** @description The user's unique username. */
      username: string
    }
    /** @description Current allocation details */
    CurrentAllocation: {
      /** @description Information about the policy in effect at the prison. */
      policy: components['schemas']['CodedDescription']
      /** @description Information about the prison. */
      prison: components['schemas']['CodedDescription']
      staffMember: components['schemas']['CurrentStaffSummary']
    }
    /** @description Prisoner Details with current and previous allocations */
    CurrentPersonStaffAllocation: {
      /**
       * @description The identifier for the prisoner.
       * @example A12345
       */
      prisonNumber: string
      /** @description Indicates if the prisoner has high complexity needs. */
      hasHighComplexityOfNeeds: boolean
      /** @description The list of current allocations for this prisoner. */
      allocations: components['schemas']['CurrentAllocation'][]
      /** @description The latest recorded events for this prisoner. */
      latestRecordedEvents: components['schemas']['RecordedEvent'][]
      /** @description The list of prison policies for this prisoner. */
      policies: components['schemas']['PolicyEnabled'][]
    }
    /** @description Summary of staff details */
    CurrentStaffSummary: {
      /**
       * Format: int64
       * @description The unique identifier for the staff member.
       */
      staffId: number
      /** @description The first name of the staff member. */
      firstName: string
      /** @description The last name of the staff member. */
      lastName: string
      /** @description The email addresses associated with the staff member. */
      emailAddresses: string[]
    }
    /** @description Recorded event details */
    RecordedEvent: {
      /** @description The prison where the event occurred. */
      prison: components['schemas']['CodedDescription']
      /**
       * @description The type of event.
       * @enum {string}
       */
      type: 'SESSION' | 'ENTRY'
      /**
       * Format: date-time
       * @description The date and time when the event occurred.
       */
      occurredAt: string
      /**
       * @description The policy tin effect at the prison where the event occurred.
       * @enum {string}
       */
      policy: 'KEY_WORKER' | 'PERSONAL_OFFICER'
      /** @description The details of the user who recorded the event. */
      author: components['schemas']['Author']
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getStaffDetails: {
    parameters: {
      query?: {
        /** @description Start date of statistics period in format YYYY-MM-DD. */
        from?: string
        /** @description End date of statistics period in format YYYY-MM-DD. */
        to?: string
        /** @description Start date of statistics period to compare within format YYYY-MM-DD. */
        comparisonFrom?: string
        /** @description End date of statistics period to compare within format YYYY-MM-DD. */
        comparisonTo?: string
      }
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
        /**
         * @description The staff member's identifier.
         * @example 123456
         */
        staffId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Staff details and statistics returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['StaffDetails']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The staff member associated with this identifier was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  modifyStaffDetails: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
        /**
         * @description The staff member's identifier.
         * @example 123456
         */
        staffId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StaffDetailsRequest']
      }
    }
    responses: {
      /** @description Staff details updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The staff member associated with this identifier was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  removeStaffRole: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
        /**
         * @description The staff member's identifier.
         * @example 123456
         */
        staffId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Staff details deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  manageAllocations: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonStaffAllocations']
      }
    }
    responses: {
      /** @description Allocations updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getPrisonPolicies: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The identifier of the prison.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Prison policies returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonPolicies']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The prison policies associated with this identifier were not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  setPrisonPolicies: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        /**
         * @description The identifier of the prison.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PrisonPolicies']
      }
    }
    responses: {
      /** @description Prison policies updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonPolicies']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The prison policies associated with this identifier were not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getPrisonConfiguration: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The identifier of the prison.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Prison configuration returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonConfigResponse']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The prison configuration associated with this identifier was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  setPrisonConfiguration: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        /**
         * @description The identifier of the prison.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PrisonConfigRequest']
      }
    }
    responses: {
      /** @description Prison configuration updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonConfigResponse']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The prison configuration associated with this identifier was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  searchStaff: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StaffSearchRequest']
      }
    }
    responses: {
      /** @description List of staff members returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['StaffSearchResponse']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  searchStaffRecordedEvents: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
        /**
         * @description The staff member's identifier.
         * @example A12345
         */
        staffId: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordedEventRequest']
      }
    }
    responses: {
      /** @description List of recorded events returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RecordedEventResponse']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  searchAllocatableStaff: {
    parameters: {
      query?: {
        /** @description Whether to include the staff member's stats in the response. */
        includeStats?: boolean
      }
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AllocatableSearchRequest']
      }
    }
    responses: {
      /** @description List of allocatable staff members returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AllocatableSearchResponse']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  searchPeople: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonSearchRequest']
      }
    }
    responses: {
      /** @description List of people returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PersonSearchResponse']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getSarContentByReference: {
    parameters: {
      query?: {
        /** @description NOMIS Prison Reference Number */
        prn?: string
        /** @description nDelius Case Reference Number */
        crn?: string
        /** @description Optional parameter denoting minimum date of event occurrence which should be returned in the response */
        fromDate?: string
        /** @description Optional parameter denoting maximum date of event occurrence which should be returned in the response */
        toDate?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Request successfully processed - content found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HmppsSubjectAccessRequestContent']
        }
      }
      /** @description Request successfully processed - no content found */
      204: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description Subject Identifier is not recognised by this service */
      209: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description The client does not have authorisation to make this request */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unexpected error occurred */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findReferenceDataForDomain: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /** @description The reference data domain required. This is case insensitive. */
        domain:
          | 'allocation-reason'
          | 'deallocation-reason'
          | 'recorded-entry-type'
          | 'staff-position'
          | 'staff-schedule-type'
          | 'staff-status'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Reference returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CodedDescription'][]
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getPrisonStatistics: {
    parameters: {
      query: {
        /** @description Start date of statistics period in format YYYY-MM-DD. */
        from: string
        /** @description End date of statistics period in format YYYY-MM-DD. */
        to: string
        /** @description Start date of statistics period to compare with in format YYYY-MM-DD. */
        comparisonFrom: string
        /** @description End date of statistics period to compare with in format YYYY-MM-DD. */
        comparisonTo: string
      }
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The identifier of the prison.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Statistics returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PrisonStats']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAllocationRecommendations: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prison's identifier.
         * @example MDI
         */
        prisonCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Recommended allocations returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RecommendedAllocations']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getAllocations: {
    parameters: {
      query?: never
      header: {
        /** @description Relevant policy for the context e.g. KEY_WORKER or PERSONAL_OFFICER */
        Policy: string
      }
      path: {
        /**
         * @description The prisoners identifier.
         * @example A12345
         */
        prisonNumber: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Allocation history returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['StaffAllocationHistory']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The allocation history associated with this identifier was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getCurrentAllocation: {
    parameters: {
      query?: {
        /** @description Whether to include contact details in response */
        includeContactDetails?: boolean
      }
      header?: never
      path: {
        /**
         * @description The prisoner's identifier
         * @example A12345
         */
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Current allocation returned. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CurrentPersonStaffAllocation']
        }
      }
      /** @description Bad request. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description The allocation data associated with this identifier was not found. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
