---
# Per environment values which override defaults in hmpps-allocate-key-workers-ui/values.yaml

generic-service:
  ingress:
    host: allocate-key-workers.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://allocate-key-workers.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
