enum AuthorisedRoles {
  OMIC_ADMIN = 'OMIC_ADMIN',
  KEYWORKER_MONITOR = 'KEYWORKER_MONITOR',
  KW_MIGRATION = 'KW_MIGRATION',
  PERSONAL_OFFICER_VIEW = 'PERSONAL_OFFICER_VIEW',
  PERSONAL_OFFICER_ALLOCATE = 'PERSONAL_OFFICER_ALLOCATE',
}

export default AuthorisedRoles
