name: Security npm dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "35 7 * * MON-FRI" # Every weekday
jobs:
  security-npm-dependency-check:
    name: Project security npm dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_npm_dependency.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: move-and-improve-alerts
    secrets: inherit
